### ISSUE TITLE
Token Names cannot be updated/changed once created

### ISSUE THREAD

**Issue by SerotoninRonin** [erizocosmico/foundry-coriolistgd#1]
While trying to change the name of your actor you are unable to update the token name via the token Prototype settings.

**Comment by erizocosmico** [comment]
Can you provide some more context for this? I can't reproduce it. Did you try from the gear icon on right-clicking the token in the canvas? I tried and I can change it from there

<img width="581" alt="Screenshot 2024-03-28 at 09 36 14" src="https://github.com/erizocosmico/foundry-coriolistgd/assets/1312023/78ba61a7-474f-402c-aafa-00835f0749a1">

**Comment by SerotoninRonin** [comment]
OK I updated to the latest version and can't reproduce any more. 
Apologies
