### ISSUE TITLE
Can't edit NPC details

### ISSUE THREAD

**Issue by jwmuk** [erizocosmico/foundry-coriolistgd#3]
Creating an NPC in v0.3.2 I am not able to edit the NPC character sheet

**Comment by erizocosmico** [comment]
NPCs are not implemented yet, but I plan on adding them soon. Short term you can use a character sheet for NPCs, since NPCs will be essentially a simplified character sheet

**Comment by erizocosmico** [comment]
NPC sheets are implemented in v0.4.0!
