### ISSUE TITLE
Health, Hope and Heart don't get calculated by attributes or are not editable?

### ISSUE THREAD

**Issue by sggt** [erizocosmico/foundry-coriolistgd#4]
I want to setup the pregenerated charakters, but I can only edit the attributes. But changes on them doesn't change the health, hope and heart ratings. They are allways rated as 4 maximum. Can it be the Foundry Language Setting to german?

![Screenshot 2024-03-31 21 05 05](https://github.com/erizocosmico/foundry-coriolistgd/assets/1477828/2ff57373-5238-44f7-ade3-165b74764304)

Foundry V11 | Build 315 -> With German as Language Setting
Module: Coriolis: The Great Dark v0.4.0
My activated modules are: 
- Dice so nice!
- Global progress clocks
- lib - Color settings
- Minimal UI
- PopOut!

**Comment by sggt** [comment]
No, the language setting, changes nothing. Problem persists.

**Comment by erizocosmico** [comment]
Thanks for spotting this! It's a bug introduced in v0.4.0. It's fixed now in v0.4.1.

**Comment by sggt** [comment]
Thanks for that super fast support! It's working now.
