### ISSUE TITLE
Lethal Option in physical injuries not working proberly 

### ISSUE THREAD

**Issue by sggt** [erizocosmico/foundry-coriolistgd#5]
The lethal option is always on *'no'* in the charakter sheet, regardless what was selected and in the edit mode always on *'yes'* regardless what was selected. Maybe variable and select are not bind? 

Screenshot of the problem:
![Injuries_bug](https://github.com/erizocosmico/foundry-coriolistgd/assets/1477828/c10b75b0-32ce-4431-829d-2d162ce95bf3)

Foundry V11 | Build 315 -> With German as Language Setting
Module: Coriolis: The Great Dark v0.4.1

**Comment by erizocosmico** [comment]
Fixed now on v0.4.2!
